services:
  # initialize directories and configs
  generate:
    image: git.dc09.xyz/chatmail/generate:latest
    volumes:
      - ./instance:/instance
      # - ./src/config:/template/config:ro
      # - ./src/web:/template/web:ro

  nginx:
    image: git.dc09.xyz/chatmail/nginx:latest
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./instance/config/nginx:/etc/nginx:ro
      - ./instance/web:/var/www/chatmail:ro
      - &vol-acme-web ./instance/data/certbot/web:/var/www/certbot
      - &vol-tls ./instance/config/tls:/tls:ro
      - &vol-newemail ./instance/socket/newemail:/run/newemail
    depends_on: &deps-gen
      generate: &dep-exit0
        condition: service_completed_successfully

  certbot:
    image: git.dc09.xyz/chatmail/certbot:latest
    restart: on-failure
    volumes:
      - ./instance/data/certbot/etc:/etc/letsencrypt
      - ./instance/data/certbot/var:/var/lib/letsencrypt
      - *vol-acme-web
      - ./instance/config/tls:/tls
      - &vol-domain ./instance/config/domain:/domain:ro
    depends_on:
      nginx: &dep-start
        condition: service_started

  postfix:
    image: git.dc09.xyz/chatmail/postfix:latest
    restart: on-failure
    ports:
      - 25:25
      - 465:465
      - 587:587
    volumes:
      - &vol-vmail ./instance/data/vmail:/home/vmail
      - &vol-postfix ./instance/data/postfix:/var/spool/postfix
      - ./instance/config/postfix:/etc/postfix:ro
      - *vol-tls
      - &vol-dkim ./instance/socket/opendkim-postfix:/var/spool/postfix/opendkim
    depends_on:
      generate: *dep-exit0
      dovecot: *dep-start
      opendkim: *dep-start
      filtermail: *dep-start
      filtermail-incoming: *dep-start

  dovecot:
    image: git.dc09.xyz/chatmail/dovecot:latest
    restart: on-failure
    ports:
      - 143:143
      - 993:993
    volumes:
      - *vol-vmail
      - *vol-postfix
      - ./instance/config/dovecot:/etc/dovecot:ro
      - *vol-tls
      - &vol-metadata ./instance/socket/metadata:/run/chatmail-metadata
      - &vol-lastlogin ./instance/socket/lastlogin:/run/chatmail-lastlogin
      - &vol-doveauth ./instance/socket/doveauth:/run/doveauth
    sysctls:
      fs.inotify.max_user_instances: 65535
      fs.inotify.max_user_watches: 65535
    depends_on:
      generate: *dep-exit0
      metadata: *dep-start
      lastlogin: *dep-start
      doveauth: *dep-start

  opendkim:
    image: git.dc09.xyz/chatmail/opendkim:latest
    restart: on-failure
    volumes:
      - ./instance/config/opendkim:/etc/opendkim
      - ./instance/config/dkimkeys:/etc/dkimkeys
      - *vol-dkim
    depends_on: *deps-gen

  filtermail:
    image: git.dc09.xyz/chatmail/filtermail:latest
    restart: on-failure
    command: outgoing
    volumes:
      - *vol-vmail
      - &vol-ini ./instance/chatmail.ini:/etc/chatmail.ini:ro
    depends_on: *deps-gen

  filtermail-incoming:
    image: git.dc09.xyz/chatmail/filtermail:latest
    restart: on-failure
    command: incoming
    volumes:
      - *vol-vmail
      - *vol-ini
    depends_on: *deps-gen

  metadata:
    image: git.dc09.xyz/chatmail/metadata:latest
    restart: on-failure
    volumes:
      - *vol-vmail
      - *vol-ini
      - *vol-metadata
      - &vol-turn ./instance/socket/chatmail-turn:/run/chatmail-turn
    depends_on: *deps-gen

  lastlogin:
    image: git.dc09.xyz/chatmail/lastlogin:latest
    restart: on-failure
    volumes:
      - *vol-vmail
      - *vol-ini
      - *vol-lastlogin
    depends_on: *deps-gen

  doveauth:
    image: git.dc09.xyz/chatmail/doveauth:latest
    restart: on-failure
    volumes:
      - *vol-vmail
      - *vol-ini
      - *vol-doveauth
    depends_on: *deps-gen

  newemail:
    image: git.dc09.xyz/chatmail/newemail:latest
    restart: on-failure
    volumes:
      - *vol-ini
      - *vol-newemail

  cron:
    image: git.dc09.xyz/chatmail/cron:latest
    restart: on-failure
    volumes:
      - *vol-vmail
      - *vol-ini
    depends_on: *deps-gen

  chatmail-turn:
    image: git.dc09.xyz/chatmail/turn:latest
    restart: on-failure
    network_mode: host  # allocates random ports for TURN
    volumes:
      - *vol-domain
      - *vol-turn

  iroh-relay:
    image: git.dc09.xyz/chatmail/iroh-relay:latest
    restart: on-failure
    # ports:
    #   - 127.0.0.1:3340:3340
